import { Button, VerticalBox, HorizontalBox, GridBox,StandardTableView, ComboBox } from "std-widgets.slint";

component Button inherits Rectangle {
    
    in-out property text <=> txt.text;
    callback clicked();
    border-radius: root.height / 2;
    border-width: 1px;
    border-color: root.background.darker(5%);
    background: touch.pressed ? #6b8282 : touch.has-hover ? #6c616c :  #456;
    height: txt.preferred-height * 1.33;
    min-width: txt.preferred-width + 20px;
    txt := Text {
        x: (parent.width - self.width)/2 + (touch.pressed ? 2px : 0);
        y: (parent.height - self.height)/2 + (touch.pressed ? 1px : 0);
        color: touch.pressed ? #fff : #eee;
    }
    touch := TouchArea { 
        clicked => {root.clicked();}
    }
}
export global TableViewPageAdapter {
    
    callback sort_ascending(int);
    callback sort_descending(int);
    
    in-out property <[[StandardListViewItem]]> row_data: [
        [ { text: "Item 1.1", clicked : {} }, { text: "Item 1.2" }, { text: "Item 1.3" }, { text: "Item 1.4" }, ],
        [ { text: "Item 2.1" }, { text: "Item 2.2" }, { text: "Item 2.3" }, { text: "Item 2.4" } ],
        [ { text: "Item 3.1" }, { text: "Item 3.2" }, { text: "Item 3.3" }, { text: "Item 3.4" }, ],
        [ { text: "Item 4.1" }, { text: "Item 4.2" }, { text: "Item 4.3" }, { text: "Item 4.4" }, ],
        [ { text: "Item 5.1" }, { text: "Item 5.2" }, { text: "Item 5.3" }, { text: "Item 5.4" }, ],
        [ { text: "Item 6.1" }, { text: "Item 6.2" }, { text: "Item 6.3" }, { text: "Item 6.4" }, ],
    ];
}
export component AppWindow inherits Window {
    in-out property <int> selected_index:0;
    in-out property <string> selected_value:"Select Invoice Issuer";
    // in-out property <string> table_data <=> table_view.model;

    callback selection_changed(int,string);
    // property <[string]> options;
    width: 1024px;
    height: 768px;
    title:"Bill Management System";
    callback  open_file();
    GridLayout {
        Row{
            Text {
                horizontal-alignment: center;
                height: 136px;
                text: "Organize your Bills";
                font-size: 24px;
                font-weight: 500;
                color: #0a0a0a;
            }
        }
        // Tableview to store invoice data
        Row{
            StandardTableView {
                // id:table_view;
                width: 1024px;
                height: 200px;
                columns: [
                    { title: "Invoice Number" },
                    { title: "Start Date" },
                    { title: "End Date"},
                    { title: "Date Due"}
                ];
                rows: TableViewPageAdapter.row_data;
            }
        }
        // ComboBox to select invoice issuer
        Row{
            ComboBox {
                model: ["Select Invoice Issuer","vodafone","nrg","epic"];
                current-index <=> root.selected_index;
                current-value <=> root.selected_value;
                selected => {root.selection_changed(root.selected_index,root.selected_value);}
            }
        }
       
        // Button to upload the pdf file via filedialog
        HorizontalLayout {
            alignment: center;
            Button {
                text: "Upload PDF";
                width: 100px;
                clicked => {root.open_file();}
                // height: 20px;
            }
            Button {
                text: "Save PDF";
                width: 100px;
                // clicked => {root.open_file();}
                // height: 20px;
            }
        }   
    }
}
